server:
  port: 8888
#port ${random.int[1024,65536]}
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&useSSL=false
#创建数据库时设置具体的database名称并且在Url路径后加上：?serverTimezone=GMT&useSSL=false在使用mabatis-generat前需要设置,serverTimezone=GMT在配置文件中有无均可，表示时区差
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

#.xml文件路径在resources包下时设置该配置
#mybatis:
#  mapper-locations: classpath:generator/*.xml

logging:
  level:
    cn.itcast.bootstart: debug