server:
  port: 8888
#port ${random.int[1024,65536]}
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#spring:
#  datasource:
#      url: jdbc:mysql://localhost:3306/studydb?useUnicode=true&characterEncoding=utf-8&useSSL=false
#      username: root
#      password: root
#      driver-class-name: com.mysql.jdbc.Driver
#配置数据源信息的全局格式，其他均为自定义格式
  datasource:
    primary:
      jdbc-url: jdbc:mysql://localhost:3306/studydb?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    secondary:
      jdbc-url: jdbc:mysql://localhost:3306/readerdb?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver

